### ISSUE TITLE
Greedy Ai nlp训练营

### ISSUE THREAD

**Issue by huangdacheng** [silverriver/Pre-Train-Based-Dialog#1]
现在做nlp的文本生成工程应用的，算法原理没有太深究，但是想优化现在的应用效果，你觉得有必要去报名Greedy Ai的课程吗

**Comment by silverriver** [comment]
如果时间允许的话还是很推荐你去报名那边的课程的。对于NLP相关的算法原理会有一个比较全面和深入的介绍，也包括文本生成领域，我认为对于拓宽思路还是很有帮助的。
